repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.3
    hooks:
      - id: ruff
        args: [--fix]
        files: ^masspcf/
      - id: ruff-format
        files: ^masspcf/

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        entry: bash -c 'find src/ include/ -name "*.cpp" -o -name "*.hpp" -o -name "*.cu" -o -name "*.cuh" | cppcheck --std=c++20 --language=c++ --suppress=missingIncludeSystem --suppress=unmatchedSuppression --suppress=normalCheckLevelMaxBranches --suppress=toomanyconfigs --suppress=checkersReport "--suppress=*:*persistence/ripser/*" -Iinclude --error-exitcode=1 --file-list=-'
        pass_filenames: false
        always_run: true
      - id: clang-tidy
        args:
          - -p=cmake-build-debug
        files: ^(src|include)/
        exclude: persistence/ripser/
        types_or: [c++]
