version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  
  jobs:
    build:
      tutorial_notebooks:
        - echo "Copying tutorial notebooks"
        - cp -R docs/tutorials_notebooks $READTHEDOCS_OUTPUT/

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
