#!/bin/bash
SITE_PKG=$(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')

cp -v masspcf/*.py "$SITE_PKG/masspcf/"
cp -v build/debug/libmpcf_cpp.so "$SITE_PKG/masspcf/mpcf_cpp.cpython-311-x86_64-linux-gnu.so"

