[build-system]
requires = [
    'setuptools>=42',
    'scikit-build>=0.13',
    'cmake>=3.20',
    'ninja',
    'pybind11',
    'numpy>=1.23',
    'numba>=0.58',
    'tqdm'
]
build-backend = 'setuptools.build_meta'

[project]
name = "masspcf"
version = "0.3.1"
authors = [ { name="Bjorn H. Wehlin", email="bwehlin@kth.se" } ]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "License :: OSI Approved :: Apache Software License",
    "Environment :: GPU :: NVIDIA CUDA",
    "Topic :: Scientific/Engineering"
]

[project.urls]
Homepage = "https://github.com/bwehlin/masspcf"
Issues = "https://github.com/bwehlin/masspcf/issues"

