[build-system]
requires = [
    'setuptools>=42',
    'scikit-build>=0.13',
    'cmake>=3.20',
    'ninja',
    'pybind11',
    'oldest-supported-numpy',
    'numba>=0.58'
]
build-backend = 'setuptools.build_meta'
