name: Analysis

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  coverage_report:
    name: Coverage report on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-24.04 ]

    env:
      BUILD_WITH_CUDA: 0
      MINIMAL_MODULE_BUILD: 1
      SKIP_STUBGEN: 1
      SKIP_BACK_COPY: 1
      ENABLE_COVERAGE: 1

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install numpy tqdm pytest gcovr # better way to do this?

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build module
        run: cmake --build build -j $(nproc)

      - name: Install module
        run: cmake --install build

      - name: Run test suites
        run: |
          cd test
          python -m pytest . || true
          ../build/mpcf_test || true
          
      - name: Create coverage report
        run: |
          mkdir covreport
          cd covreport
          gcovr --gcov-ignore-parse-errors=negative_hits.warn_once_per_file -r . --object-directory ../build --filter ../include/ --filter ../src/ --html-details coverage.html --print-summary
          gcovr --gcov-ignore-parse-errors=negative_hits.warn_once_per_file -r . --object-directory ../build --filter ../include/ --filter ../src/ --markdown >> $GITHUB_STEP_SUMMARY

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./covreport

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: covreport/*
          retention-days: 1

  memory_check:
    name: Memory check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-24.04 ]

    env:
      BUILD_WITH_CUDA: 0
      MINIMAL_MODULE_BUILD: 1
      SKIP_STUBGEN: 1
      SKIP_BACK_COPY: 1
      PYTHONMALLOC: malloc

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install numpy tqdm pytest ValgrindCI # better way to do this?

      - name: Install Valgrind and Debug Symbols
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind libc6-dbg

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build module
        run: cmake --build build -j $(nproc)

      - name: Install module
        run: cmake --install build

      - name: Create reports directory
        run: mkdir test/reports

      - name: Run valgrind on Pytest
        run: |
          cd test
          valgrind --xml=yes --xml-file=./reports/vg-pytest.xml python -m pytest . -vv -s || true
          valgrind-ci ./reports/vg-pytest.xml --summary >> $GITHUB_STEP_SUMMARY
          valgrind-ci ./reports/vg-pytest.xml --output-dir=./reports/vg_pytest

      - name: Run valgrind on GTest
        run: |
          cd test
          valgrind --xml=yes --xml-file=./reports/vg-gtest.xml ../build/mpcf_test || true
          valgrind-ci ./reports/vg-gtest.xml --summary >> $GITHUB_STEP_SUMMARY
          valgrind-ci ./reports/vg-gtest.xml --output-dir=./reports/vg_gtest

      - uses: actions/upload-artifact@v4
        with:
          name: valgrind-output
          path: test/reports/*
          retention-days: 1



