name: BuildAndPublishTestPyPI

on: [workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/wheels.yaml

  compare:
    runs-on: ubuntu-latest
    needs: build
    if: github.actor == 'bwehlin'

    steps:
      - uses: actions/checkout@v4

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: cpu-wheels
          path: dist/

      - name: Compare wheels
        run: |
          set -o pipefail
          echo '```' >> $GITHUB_STEP_SUMMARY
          python -u .github/scripts/compare_wheels.py -v dist/ | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  publish:
    runs-on: ubuntu-latest
    needs: compare
    if: github.actor == 'bwehlin'
    environment:
      name: pypi-test
      url: https://test.pypi.org/p/masspcf
    permissions:
      id-token: write

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: cpu-wheels
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/