name: BuildSdist

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_sdist:
    name: Build & test source distribution
    runs-on: [self-hosted, gpu, cuda12]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Set up Python
        run: |
          python3 -m venv --system-site-packages ${{github.workspace}}/.venv
          echo "${{github.workspace}}/.venv/bin" >> $GITHUB_PATH

      - name: Build sdist
        run: python3 -m build --sdist

      - name: Install from sdist
        run: python3 -m pip install dist/masspcf-*.tar.gz --force-reinstall
        env:
          BUILD_WITH_CUDA: "0"

      - name: Test sdist install
        working-directory: test
        run: python3 -m pytest python -x -q

      - uses: actions/upload-artifact@v6
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 2
