name: BuildWheels

on: [workflow_dispatch]

jobs:
  build_wheels_CPU:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os [ubuntu-22.04, windows-2019]
        #os: [ubuntu-22.04, ubuntu-22.04-arm, windows-2019, macos-13, macos-14]
    
    env: 
      BUILD_WITH_CUDA: 0

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Change project name (Windows)
        run: powershell -Command "(gc pyproject.toml) -replace 'masspcf', 'masspcf-cpu' | Out-File -encoding ASCII pyproject.toml"
        if: runner.os == 'Windows'
      
      - name: Change project name (UNIX)
        run: sed -i -e 's/masspcf/masspcf-cpu/g' pyproject.toml
        if: runner.os != 'Windows'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: "*musl*"
          CIBW_ARCHS_MACOS: "native"
          CIBW_ARCHS_LINUX: "native"
          CIBW_ARCHS_WINDOWS: "native"
          CIBW_ENVIRONMENT: BUILD_WITH_CUDA=0 MACOSX_DEPLOYMENT_TARGET=10.13
      
      - uses: actions/upload-artifact@v4
        with: 
          name: cpu-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          retention-days: 1
  
  merge_cpu_artifacts:
    runs-on: ubuntu-latest
    needs: build_wheels_CPU
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: cpu-wheels
          retention-days: 2
    
