name: BuildWheels

on: [workflow_dispatch]

jobs:
  build_wheels_CPU:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, windows-2019, macos-14]
    
    steps:
      - name: Set compiler
        if: runner.os == 'OSX'
        run:
          setenv CXX gcc-14

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: "*musl*"
          CIBW_ARCHS_MACOS: "universal2 arm64"
          CIBW_ARCHS_LINUX: "native"
          CIBW_ARCHS_WINDOWS: "native"
          CIBW_ENVIRONMENT: BUILD_WITH_CUDA=0
      
      - uses: actions/upload-artifact@v4
        with: 
          name: cpu-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
